spring:
  messages:
    basename: i18n/bundle
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    data: main-data.sql
    initialization-mode: EMBEDDED

  jpa:
    generate-ddl: false
    hibernate:
      hbm2ddl:
        auto: none
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: ERROR