spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin

  jpa:
    generate-ddl: false
    hibernate:
      hbm2ddl:
        auto: none
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: ERROR