DROP TABLE IF EXISTS AUTHOR CASCADE;
DROP TABLE IF EXISTS GENRE CASCADE;
DROP TABLE IF EXISTS BOOK CASCADE;

CREATE TABLE AUTHOR(ID INT AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255));

CREATE TABLE GENRE(ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255));

CREATE TABLE BOOK(ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(255),
AUTHOR_ID INT,
GENRE_ID INT,
FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(GENRE_ID) REFERENCES GENRE(ID) ON DELETE CASCADE ON UPDATE CASCADE);