DROP TABLE IF EXISTS "AUTHORS" cascade;
DROP TABLE IF EXISTS "GENRES" cascade;
DROP TABLE IF EXISTS "BOOKS" cascade;

create TABLE "AUTHORS" (
  "ID" SERIAL PRIMARY KEY NOT NULL,
  "FIRST_NAME" varchar NOT NULL,
  "LAST_NAME" varchar NOT NULL,
  "CREATED_AT" datetime NOT NULL DEFAULT (now())
);

create TABLE "GENRES" (
  "ID" SERIAL PRIMARY KEY NOT NULL,
  "GENRE_NAME" varchar NOT NULL,
  "CREATED_AT" datetime NOT NULL DEFAULT (now())
);

create TABLE "BOOKS" (
  "ID" SERIAL PRIMARY KEY NOT NULL,
  "BOOK_TITLE" varchar NOT NULL,
  "CREATED_AT" datetime NOT NULL DEFAULT (now()),
  "GENRE_ID" int NOT NULL,
  "AUTHOR_ID" int NOT NULL
);

alter table "BOOKS" add FOREIGN KEY ("GENRE_ID") REFERENCES "GENRES" ("ID");

alter table "BOOKS" add FOREIGN KEY ("AUTHOR_ID") REFERENCES "AUTHORS" ("ID");